### ISSUE TITLE
Example how to specify a list of repos

### ISSUE THREAD

**Issue by jeanCarloMachado** [getyourguide/auto-pr#108]
Thanks for this great tool!

I wonder how can I specific a deterministic list of repos?
Can you provide some more docs in that section? Thank you!

**Comment by tplass-ias** [comment]
alternatively pass a list of exact strings to match:

```yaml
repositories: # Rules that define what repos to update
  - mode: add
    match_owner: foo
    match_name:
      - bar
      - bazz
```
